import Navbar from '@/components/Navbar'
import type { Metadata } from "next";
import "@/app/globals.css";
import Footer from '@/components/Footer';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <div
        className="flex flex-col min-h-screen bg-gray-50"
      >
        {/* 🔹 نوار بالا */}
        <Navbar />

        {/* 🔹 محتوای اصلی */}

        <main className="flex flex-col items-center gap-16 mt-16 grow">
          {children}
        </main>


        {/* 🔹 فوتر همیشه پایین */}
        <Footer />
      </div>

  );
}
